### ISSUE TITLE
Error: statfs /var/lib/zerotier-one: no such file or directory

### ISSUE THREAD

**Issue by aaylnx** [zyclonite/zerotier-docker#11]
I'm trying to run this zerotier container on a Fedora Silverblue

I'm using the following command to do so

`podman run --name zerotier-one --device=/dev/net/tun --net=host   --cap-add=NET_ADMIN --cap-add=SYS_ADMIN   -v /var/lib/zerotier-one:/var/lib/zerotier-one zyclonite/zerotier`

When I do this `quay.io/zyclonite/zerotier:latest` is downloaded but before it launches I get the following error

`Error: statfs /var/lib/zerotier-one: no such file or directory`

I get the same error if I download images from other sources. I'm not sure what to do. Any thoughts are appreciated.

**Comment by zyclonite** [comment]
i have not tried silverblue yet but i would check three things:

1. does `/var/lib/zerotier-one` exist on your host?
2. is selinux enabled and if does the directory have a security context for containers? (e.g. `container_file_t`)
3. try mounting the volume with `-v /var/lib/zerotier-one:/var/lib/zerotier-one:z` (the `:z` is important)
