### ISSUE TITLE
Docker command to join network does not work

### ISSUE THREAD

**Issue by 3nigm4** [zyclonite/zerotier-docker#2]
Hey there,

when I run
`$ sudo docker exec zerotier-one /zerotier-cli join 8056c2e21c000001`

I get the following error:
`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/zerotier-cli": stat /zerotier-cli: no such file or directory: unknown
`

but when I do:

`$ sudo docker exec -it zerotier-one /bin/sh`

and then:

`# zerotier-cli join 8056c2e21c000001`

I get:

`200 join OK`

maybe because of the OCI Runtime?

**Comment by zyclonite** [comment]
@3nigm4 you are right, this was wrong in the readme

you can just skip the leading `/` for the `zerotier-cli` and it should work

updated the readme: https://github.com/zyclonite/zerotier-docker/commit/9b5623ac02c9f4715401b404361055a96a848839

**Comment by 3nigm4** [comment]
thank you, it works now!
