### ISSUE TITLE
自建 Zerotier Planet 连接不稳定，间歇性Offlin

### ISSUE THREAD

**Issue by EmericLee** [zyclonite/zerotier-docker#29]
自建Planet，并且实现了客户端连接。

但是经常性的出现所有`peer`无法连接问题，客户端处于`REQUESTING_CONFIGURATION`， `zerotier-cli info` 返回  `offline`。同时，服务端（ztncui）的Peer status不在更新，即使掉线的Peer，也仍然有些显示为 `online`.

问题可能出在哪里？防火墙不应该间歇性屏蔽端口吧？

**Comment by zyclonite** [comment]
i would recommend posting to the zerotier community, this is not related to the container.

https://discuss.zerotier.com/
